import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { planGeneratedFiles } from "../src/generator/generate.js";
import type { MoeiconsConfigFile } from "../src/project/config.js";

/**
 * E2E-07: global theme-switch. The generated registry must map theme -> icon
 * with style groups; the proxy components must resolve the current theme. A
 * missing icon follows the configured fallback policy.
 */

const config: MoeiconsConfigFile = {
  schemaVersion: 1,
  framework: "react",
  outputDir: "src/moeicons",
  defaultTheme: "outline",
  themes: {
    outline: { styles: ["outline"], className: "text-zinc-700" },
    solid: { styles: ["fill"], className: "text-zinc-800" },
  },
  icons: ["arrow-chevron-right", "user-circle"],
  missingIconPolicy: "fallback",
};

describe("E2E-07 theme-switch contract", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "e2e-theme-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("generates a theme-keyed registry mapping theme -> icon", () => {
    const plan = planGeneratedFiles(config, "src/moeicons");
    expect(plan.ok).toBe(true);
    if (!plan.ok) return;
    const registry = plan.files.find((f) => f.path.endsWith("registry.ts"))?.content ?? "";
    expect(registry).toContain('"outline"');
    expect(registry).toContain('"solid"');
    expect(registry).toContain("ArrowChevronRight");
    expect(registry).toContain("UserCircle");
  });

  it("generates proxy components that resolve the current theme at runtime", () => {
    const plan = planGeneratedFiles(config, "src/moeicons");
    expect(plan.ok).toBe(true);
    if (!plan.ok) return;
    const proxy = plan.files.find((f) => f.path.endsWith("icons/ArrowChevronRight.tsx"))?.content ?? "";
    // proxy carries the canonical icon id for runtime resolution
    expect(proxy).toContain('data-moeicon="arrow-chevron-right"');
    // proxy accepts user props (className/size/strokeWidth) passthrough
    expect(proxy).toContain("props");
  });

  it("missing icons follow the configured fallback policy", () => {
    expect(config.missingIconPolicy).toBe("fallback");
    // a partial selection still generates only requested icons
    const partial = { ...config, icons: ["arrow-chevron-right"] };
    const plan = planGeneratedFiles(partial, "src/moeicons");
    expect(plan.ok).toBe(true);
    if (!plan.ok) return;
    const paths = plan.files.map((f) => f.path);
    expect(paths.some((p) => p.endsWith("icons/ArrowChevronRight.tsx"))).toBe(true);
    expect(paths.some((p) => p.endsWith("icons/UserCircle.tsx"))).toBe(false);
  });

  it("writes the generated tree deterministically", async () => {
    const plan = planGeneratedFiles(config, "src/moeicons");
    expect(plan.ok).toBe(true);
    if (!plan.ok) return;
    const { mkdirSync } = await import("node:fs");
    const { dirname } = await import("node:path");
    for (const file of plan.files) {
      const full = join(dir, file.path);
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, file.content);
    }
    expect(existsSync(join(dir, "src", "moeicons", "registry.ts"))).toBe(true);
    expect(existsSync(join(dir, "src", "moeicons", "icons", "ArrowChevronRight.tsx"))).toBe(true);
    const registry = readFileSync(join(dir, "src", "moeicons", "registry.ts"), "utf8");
    expect(registry).toContain("Generated by moeicons CLI");
  });
});
