import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdtempSync,
  writeFileSync,
  readFileSync,
  rmSync,
  existsSync,
  mkdirSync,
  renameSync,
  readdirSync,
  copyFileSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { main } from "../src/cli.js";
import { executeGeneratedFilesDir, executeManagedReconcile } from "../src/project/install.js";
import { parse } from "jsonc-parser";
import { runGenerateUseCase } from "../src/core/generate.js";
import {
  parseInstallMetadata,
  serializeInstallMetadata,
  sha256Bytes,
} from "../src/project/install-metadata.js";

const GENERATED_HEADER =
  "// Generated by moeicons CLI. Do not edit manually; re-run `moeicons generate`.";

/**
 * CLI-12/CLI-13: config generation and React proxy generation.
 * `moeicons init` creates moeicons.config.json; `moeicons generate` writes the
 * owned proxy files into the configured output dir.
 */

function makeRuntime() {
  const out: string[] = [];
  const err: string[] = [];
  let cwd = "";
  return {
    runtime: {
      cwd: () => cwd,
      stdout: (text: string) => out.push(text),
      stderr: (text: string) => err.push(text),
      env: {},
      isTTY: () => false,
      readLine: async () => "",
      readKey: async () => "",
    },
    out,
    err,
    setCwd: (d: string) => {
      cwd = d;
    },
  };
}

describe("CLI init + generate", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "cli-init-"));
    writeFileSync(join(dir, "package.json"), JSON.stringify({ name: "fixture", version: "1.0.0" }));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("init creates a v2 config and never overwrites an existing one", async () => {
    const { runtime, setCwd } = makeRuntime();
    setCwd(dir);
    const code = await main(["init", "--json"], runtime);
    expect(code).toBe(0);
    const configPath = join(dir, "moeicons.config.jsonc");
    expect(existsSync(configPath)).toBe(true);
    const config = parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
    expect(config.schemaVersion).toBe(2);
    expect(config.target).toBe("react");

    // second init must not overwrite
    const before = readFileSync(configPath, "utf8");
    await main(["init"], runtime);
    expect(readFileSync(configPath, "utf8")).toBe(before);
  });

  it("init detects a Vue dependency instead of writing a React config", async () => {
    writeFileSync(
      join(dir, "package.json"),
      JSON.stringify({ name: "vue-fixture", version: "1.0.0", dependencies: { vue: "3.5.0" } }),
    );
    const { runtime, setCwd } = makeRuntime();
    setCwd(dir);
    expect(await main(["init", "--json"], runtime)).toBe(0);
    const config = parse(readFileSync(join(dir, "moeicons.config.jsonc"), "utf8")) as Record<
      string,
      unknown
    >;
    expect(config.target).toBe("vue");
  });

  it("generate writes proxy files into the configured output dir", async () => {
    const { runtime, setCwd } = makeRuntime();
    setCwd(dir);
    await main(["init"], runtime);
    // add icons to the config so generation has something to emit
    const configPath = join(dir, "moeicons.config.jsonc");
    const config = parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
    config.icons = ["arrow-bold-right", "user-account-circle"];
    writeFileSync(configPath, JSON.stringify(config, null, 2));

    const code = await main(["generate", "--json"], runtime);
    expect(code).toBe(0);
    expect(existsSync(join(dir, "src", "moeicons", "registry.ts"))).toBe(true);
    expect(existsSync(join(dir, "src", "moeicons", "icons", "ArrowBoldRight.tsx"))).toBe(true);
    expect(existsSync(join(dir, "src", "moeicons", "icons", "UserAccountCircle.tsx"))).toBe(true);
    const registry = readFileSync(join(dir, "src", "moeicons", "registry.ts"), "utf8");
    expect(registry).toContain("ArrowBoldRight");
  });

  it("generate fails cleanly when no config exists", async () => {
    const { runtime, out, setCwd } = makeRuntime();
    setCwd(dir);
    const code = await main(["generate", "--json"], runtime);
    expect(code).toBe(1);
    const parsed = JSON.parse(out.join("")) as { ok: boolean; code: string; message: string };
    expect(parsed.ok).toBe(false);
    expect(parsed.code).toBe("VALIDATION_ERROR");
    expect(parsed.message).toContain("missing");
  });

  it("does not replace user-owned files in the output directory", async () => {
    const { runtime, setCwd } = makeRuntime();
    setCwd(dir);
    await main(["init"], runtime);
    const configPath = join(dir, "moeicons.config.jsonc");
    const config = parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
    config.icons = ["ui-search"];
    writeFileSync(configPath, JSON.stringify(config, null, 2));

    const userFile = join(dir, "src", "moeicons", "user-note.md");
    mkdirSync(join(dir, "src", "moeicons"), { recursive: true });
    writeFileSync(userFile, "keep me");
    expect(await main(["generate"], runtime)).toBe(0);
    expect(readFileSync(userFile, "utf8")).toBe("keep me");
  });

  it("reconciles only metadata-owned resources, removes stale entries and preserves user files", async () => {
    const { runtime, setCwd } = makeRuntime();
    setCwd(dir);
    await main(["init"], runtime);
    const configPath = join(dir, "moeicons.config.jsonc");
    const config = parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
    config.icons = ["ui-search"];
    writeFileSync(configPath, JSON.stringify(config, null, 2));
    const catalog = "catalog bytes";
    const stale = `${GENERATED_HEADER}\nstale`;
    mkdirSync(join(dir, ".moeicons"), { recursive: true });
    mkdirSync(join(dir, "src", "moeicons", "icons"), { recursive: true });
    writeFileSync(join(dir, ".moeicons", "catalog.json"), catalog);
    writeFileSync(join(dir, "src", "moeicons", "icons", "Old.tsx"), stale);
    writeFileSync(join(dir, "src", "moeicons", "user-note.md"), "keep me");
    writeFileSync(
      join(dir, ".moeicons", "install-metadata.json"),
      serializeInstallMetadata({
        schemaVersion: 1,
        artifactVersion: "1.0.0",
        tier: "free",
        target: "react",
        descriptorSha256: "a".repeat(64),
        artifactSha256: "b".repeat(64),
        catalogSha256: sha256Bytes(catalog),
        installedAt: "2026-08-24T00:00:00Z",
        managedFiles: {
          ".moeicons/catalog.json": sha256Bytes(catalog),
          "src/moeicons/icons/Old.tsx": sha256Bytes(stale),
        },
      }),
    );
    const context = {
      cwd: dir,
      env: {},
      signal: new AbortController().signal,
      now: () => new Date(),
      ui: {
        select: async () => undefined,
        confirm: async () => undefined,
        text: async () => undefined,
        note() {},
        progress: () => ({ stop() {} }),
      },
    };
    const fs = {
      mkdirSync,
      writeFileSync,
      readFileSync,
      existsSync,
      renameSync,
      rmSync,
      readdirSync,
      copyFileSync,
    };
    const result = await runGenerateUseCase(context, fs, { noTailwind: true, reconcileInstalled: true });
    expect(result.ok).toBe(true);
    expect(existsSync(join(dir, "src", "moeicons", "icons", "Old.tsx"))).toBe(false);
    expect(existsSync(join(dir, "src", "moeicons", "icons", "UiSearch.tsx"))).toBe(true);
    expect(readFileSync(join(dir, "src", "moeicons", "user-note.md"), "utf8")).toBe("keep me");
    const next = parseInstallMetadata(
      readFileSync(join(dir, ".moeicons", "install-metadata.json"), "utf8"),
    );
    expect(next?.managedFiles["src/moeicons/icons/Old.tsx"]).toBeUndefined();
    expect(next?.managedFiles["src/moeicons/icons/UiSearch.tsx"]).toMatch(/^[a-f0-9]{64}$/);
  });

  it("rejects a user-modified managed file with zero resource modification", async () => {
    const { runtime, setCwd } = makeRuntime();
    setCwd(dir);
    await main(["init"], runtime);
    const configPath = join(dir, "moeicons.config.jsonc");
    const config = parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
    config.icons = ["ui-search"];
    writeFileSync(configPath, JSON.stringify(config, null, 2));
    mkdirSync(join(dir, ".moeicons"), { recursive: true });
    mkdirSync(join(dir, "src", "moeicons"), { recursive: true });
    writeFileSync(join(dir, ".moeicons", "catalog.json"), "catalog");
    writeFileSync(join(dir, "src", "moeicons", "old.ts"), "user edit");
    writeFileSync(
      join(dir, ".moeicons", "install-metadata.json"),
      serializeInstallMetadata({
        schemaVersion: 1,
        artifactVersion: "1.0.0",
        tier: "free",
        target: "react",
        descriptorSha256: "a".repeat(64),
        artifactSha256: "b".repeat(64),
        catalogSha256: sha256Bytes("catalog"),
        installedAt: "2026-08-24T00:00:00Z",
        managedFiles: {
          ".moeicons/catalog.json": sha256Bytes("catalog"),
          "src/moeicons/old.ts": sha256Bytes("original"),
        },
      }),
    );
    const beforeMetadata = readFileSync(join(dir, ".moeicons", "install-metadata.json"), "utf8");
    const context = {
      cwd: dir,
      env: {},
      signal: new AbortController().signal,
      now: () => new Date(),
      ui: {
        select: async () => undefined,
        confirm: async () => undefined,
        text: async () => undefined,
        note() {},
        progress: () => ({ stop() {} }),
      },
    };
    const result = await runGenerateUseCase(
      context,
      {
        mkdirSync,
        writeFileSync,
        readFileSync,
        existsSync,
        renameSync,
        rmSync,
        readdirSync,
        copyFileSync,
      },
      { noTailwind: true, reconcileInstalled: true },
    );
    expect(result).toMatchObject({ ok: false });
    expect(readFileSync(join(dir, "src", "moeicons", "old.ts"), "utf8")).toBe("user edit");
    expect(readFileSync(join(dir, ".moeicons", "install-metadata.json"), "utf8")).toBe(
      beforeMetadata,
    );
  });

  it("rolls back cross-directory reconcile when commit fails", () => {
    const old = join(dir, "src", "moeicons", "old.ts");
    mkdirSync(join(old, ".."), { recursive: true });
    writeFileSync(old, "old");
    let renames = 0;
    expect(() =>
      executeManagedReconcile(
        dir,
        { "src/moeicons/old.ts": "new", ".moeicons/install-metadata.json": "meta" },
        [],
        {
          mkdirSync,
          writeFileSync,
          readFileSync,
          existsSync,
          rmSync,
          readdirSync,
          copyFileSync,
          renameSync: (...args: Parameters<typeof renameSync>) => {
            renames += 1;
            if (renames === 3) throw new Error("commit failed");
            return renameSync(...args);
          },
        },
      ),
    ).toThrow("commit failed");
    expect(readFileSync(old, "utf8")).toBe("old");
    expect(existsSync(join(dir, ".moeicons", "install-metadata.json"))).toBe(false);
  });

  it("restores generated files when the staging→output rename fails", () => {
    const output = join(dir, "src", "moeicons");
    const oldFile = join(output, "old.ts");
    mkdirSync(output, { recursive: true });
    writeFileSync(oldFile, "old");
    const real = {
      mkdirSync,
      writeFileSync,
      readFileSync,
      existsSync,
      renameSync,
      rmSync,
      readdirSync,
      copyFileSync,
    };
    let renames = 0;
    expect(() =>
      executeGeneratedFilesDir(
        [
          { path: "src/moeicons/old.ts", content: "new content" },
          { path: "src/moeicons/new.ts", content: "new file" },
        ],
        dir,
        "src/moeicons",
        {
          ...real,
          renameSync: (...args: Parameters<typeof renameSync>) => {
            renames += 1;
            // Fail on the second rename (staging → output), after backup already done.
            if (renames === 2) throw new Error("simulated rename failure");
            return renameSync(...args);
          },
        },
      ),
    ).toThrow("simulated rename failure");
    // The original file must be restored.
    expect(readFileSync(oldFile, "utf8")).toBe("old");
    expect(existsSync(join(output, "new.ts"))).toBe(false);
  });

  it("removes stale managed files that are absent from the new plan", () => {
    const output = join(dir, "src", "moeicons");
    mkdirSync(join(output, "icons"), { recursive: true });
    writeFileSync(join(output, "registry.ts"), `${GENERATED_HEADER}\nold registry`);
    writeFileSync(join(output, "icons", "OldOnly.tsx"), `${GENERATED_HEADER}\nold proxy`);
    writeFileSync(join(output, "user-note.md"), "keep me");

    executeGeneratedFilesDir(
      [
        { path: "src/moeicons/registry.ts", content: "new registry" },
        { path: "src/moeicons/icons/NewOnly.tsx", content: "new proxy" },
      ],
      dir,
      "src/moeicons",
      {
        mkdirSync,
        writeFileSync,
        readFileSync,
        existsSync,
        renameSync,
        rmSync,
        readdirSync,
        copyFileSync,
      },
    );

    expect(readFileSync(join(output, "registry.ts"), "utf8")).toBe("new registry");
    expect(readFileSync(join(output, "icons", "NewOnly.tsx"), "utf8")).toBe("new proxy");
    expect(existsSync(join(output, "icons", "OldOnly.tsx"))).toBe(false);
    expect(readFileSync(join(output, "user-note.md"), "utf8")).toBe("keep me");
  });

  it("cleans leftover .staging and .bak directories before a new run", () => {
    const output = join(dir, "src", "moeicons");
    const staging = `${output}.staging`;
    const backup = `${output}.bak`;
    mkdirSync(join(staging, "icons"), { recursive: true });
    mkdirSync(join(backup, "icons"), { recursive: true });
    writeFileSync(join(staging, "icons", "stale.tsx"), "stale staging file");
    writeFileSync(join(backup, "icons", "stale.tsx"), "stale backup file");
    mkdirSync(output, { recursive: true });
    writeFileSync(join(output, "user-note.md"), "keep me");

    executeGeneratedFilesDir(
      [{ path: "src/moeicons/registry.ts", content: "new registry" }],
      dir,
      "src/moeicons",
      {
        mkdirSync,
        writeFileSync,
        readFileSync,
        existsSync,
        renameSync,
        rmSync,
        readdirSync,
        copyFileSync,
      },
    );

    expect(existsSync(staging)).toBe(false);
    expect(existsSync(backup)).toBe(false);
    expect(readFileSync(join(output, "registry.ts"), "utf8")).toBe("new registry");
    expect(readFileSync(join(output, "user-note.md"), "utf8")).toBe("keep me");
  });

  it("preserves nested user-owned files when managed files share nearby paths", () => {
    const output = join(dir, "src", "moeicons");
    mkdirSync(join(output, "icons", "notes"), { recursive: true });
    writeFileSync(join(output, "icons", "Legacy.tsx"), `${GENERATED_HEADER}\nold managed file`);
    writeFileSync(join(output, "icons", "notes", "README.md"), "keep nested note");

    executeGeneratedFilesDir(
      [{ path: "src/moeicons/icons/NewIcon.tsx", content: "new managed file" }],
      dir,
      "src/moeicons",
      {
        mkdirSync,
        writeFileSync,
        readFileSync,
        existsSync,
        renameSync,
        rmSync,
        readdirSync,
        copyFileSync,
      },
    );

    expect(existsSync(join(output, "icons", "Legacy.tsx"))).toBe(false);
    expect(readFileSync(join(output, "icons", "NewIcon.tsx"), "utf8")).toBe("new managed file");
    expect(readFileSync(join(output, "icons", "notes", "README.md"), "utf8")).toBe(
      "keep nested note",
    );
  });
});
