import { describe, it, expect } from "vitest";
import { planGeneratedFiles, toPascalCase } from "../src/generator/generate.js";
import type { MoeiconsConfigFile } from "../src/project/config.js";

const vueConfig: MoeiconsConfigFile = {
  schemaVersion: 1,
  tier: "free",
  framework: "vue",
  outputDir: "src/moeicons",
  defaultTheme: "outline",
  themes: { outline: { styleGroup: "moe-outline" }, solid: { styleGroup: "moe-solid" } },
  icons: ["arrow-bold-right", "user-account-circle"],
  missingIconPolicy: "fallback",
};

describe("planGeneratedFiles (Vue)", () => {
  it("generates Vue-only file layout (no .tsx, no JSX.Element)", () => {
    const result = planGeneratedFiles(vueConfig, "src/moeicons");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const paths = result.files.map((f) => f.path);
    expect(paths).toContain("src/moeicons/types.ts");
    expect(paths).toContain("src/moeicons/theme.ts");
    expect(paths).toContain("src/moeicons/registry.ts");
    expect(paths).toContain("src/moeicons/provider.ts");
    expect(paths).toContain("src/moeicons/composable.ts");
    expect(paths).toContain("src/moeicons/icons/ArrowBoldRight.ts");
    expect(paths).toContain("src/moeicons/icons/UserAccountCircle.ts");
    expect(paths).toContain("src/moeicons/index.ts");
    // React artifacts must not appear for Vue configs
    expect(paths.some((p) => p.endsWith(".tsx"))).toBe(false);
    const allContent = result.files.map((f) => f.content).join("\n");
    expect(allContent).not.toContain("JSX.Element");
  });

  it("generates a typed provider, composable, and injection key", () => {
    const result = planGeneratedFiles(vueConfig, "src/moeicons");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const provider = result.files.find((f) => f.path.endsWith("provider.ts"))?.content ?? "";
    const composable = result.files.find((f) => f.path.endsWith("composable.ts"))?.content ?? "";
    const theme = result.files.find((f) => f.path.endsWith("theme.ts"))?.content ?? "";
    expect(provider).toContain("MoeiconsProvider");
    expect(provider).toContain("provide");
    expect(provider).toContain("ref<Theme>");
    expect(composable).toContain("useMoeiconsTheme");
    expect(composable).toContain("inject");
    expect(theme).toContain("MOEICONS_THEME_KEY");
    expect(theme).toContain("InjectionKey<MoeiconsThemeState>");
  });

  it("generates proxy components that read the injected theme reactively", () => {
    const result = planGeneratedFiles(vueConfig, "src/moeicons");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const proxy = result.files.find((f) => f.path.endsWith("icons/ArrowBoldRight.ts"))?.content ?? "";
    expect(proxy).toContain("defineComponent");
    expect(proxy).toContain("inject");
    expect(proxy).toContain("computed");
    expect(proxy).toContain("registry[");
    expect(proxy).toContain("state?.theme.value");
  });

  it("generates a registry typed with Vue Component", () => {
    const result = planGeneratedFiles(vueConfig, "src/moeicons");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const registry = result.files.find((f) => f.path.endsWith("registry.ts"))?.content ?? "";
    expect(registry).toContain('import type { Component } from "vue"');
    expect(registry).toContain("readonly ArrowBoldRight: Component");
    expect(registry).toContain('"outline"');
    expect(registry).toContain('"solid"');
  });

  it("preserves hyphens and canonical ids in Vue proxy output", () => {
    const result = planGeneratedFiles(vueConfig, "src/moeicons");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const proxy = result.files.find((f) => f.path.endsWith("icons/ArrowBoldRight.ts"))?.content ?? "";
    expect(proxy).toContain("ArrowBoldRight");
    expect(toPascalCase("arrow-bold-right")).toBe("ArrowBoldRight");
  });

  it("writes generated Vue files deterministically", async () => {
    const a = planGeneratedFiles(vueConfig, "src/moeicons");
    const b = planGeneratedFiles(vueConfig, "src/moeicons");
    expect(a.ok && b.ok).toBe(true);
    if (!a.ok || !b.ok) return;
    expect(a.files).toEqual(b.files);
    for (const f of a.files) {
      expect(f.content).toContain("Generated by moeicons CLI");
    }
  });
});
