#!/usr/bin/env node
/**
 * Dev-only: render "MOEICONS" with figlet and write src/ui/banner.ts.
 * Runtime CLI never imports figlet.
 */
import figlet from "figlet";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const text = figlet.textSync("MOEICONS", { font: "Standard", horizontalLayout: "default" });
const banner = text.replace(/\s+$/gm, "").replace(/\n+$/, "") + "\n";
const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "ui", "banner.ts");
const literal = JSON.stringify(`\n${banner}`);

writeFileSync(
  outPath,
  [
    "/** ASCII banner generated by scripts/generate-banner.mjs (figlet, Standard font). Do not edit by hand. */",
    `export const MOEICONS_BANNER = ${literal};`,
    "",
    "export function renderBannerText(): string {",
    "  return `${MOEICONS_BANNER}\\nMoeicons icon library — CLI\\n`;",
    "}",
    "",
  ].join("\n"),
);
process.stdout.write(`wrote ${outPath}\n`);
