#!/usr/bin/env node
/**
 * Dev-only: render "MOEICONS" with figlet and write src/ui/generated/wordmark.ts.
 * Runtime CLI never imports figlet. This script must not overwrite src/ui/banner.ts.
 */
import figlet from "figlet";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const text = figlet.textSync("MOEICONS", { font: "Standard", horizontalLayout: "default" });
const banner = text.replace(/\s+$/gm, "").replace(/\n+$/, "") + "\n";
const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "ui", "generated");
const outPath = join(outDir, "wordmark.ts");
mkdirSync(outDir, { recursive: true });
const literal = JSON.stringify(`\n${banner}`);

writeFileSync(
  outPath,
  [
    "/** ASCII wordmark generated by scripts/generate-banner.mjs (figlet, Standard font). Do not edit by hand. */",
    `export const MOEICONS_BANNER = ${literal};`,
    "",
  ].join("\n"),
);
process.stdout.write(`wrote ${outPath}\n`);
