/** Generated helper text for user projects (H1/H2). Versions locked by CLI constants. */

export const CLSX_VERSION_RANGE = "^2.1.1";
export const TAILWIND_MERGE_VERSION_RANGE = "^2.5.2";

export const CN_HELPER_SOURCE = `// Generated by moeicons CLI. Do not edit manually; re-run \`moeicons generate\`.
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
`;

export function sizeToTailwindClass(sizePx: number): string {
  return `w-[${sizePx}px] h-[${sizePx}px]`;
}
