import type { MoeiconsConfigFile } from "../project/config.js";

/**
 * React/Vue proxy generation. Purely returns owned file paths/content for
 * types, registry, provider/plugin, proxies and barrel exports. Rejects
 * duplicate PascalCase names and missing fallback.
 */

export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
}

export interface GenerationResult {
  readonly ok: true;
  readonly files: GeneratedFile[];
}

export interface GenerationError {
  readonly ok: false;
  readonly errors: string[];
}

export type GenerationOutcome = GenerationResult | GenerationError;

/** kebab → Pascal: `arrow-chevron-right` → `ArrowChevronRight`. */
export function toPascalCase(id: string): string {
  return id
    .split("-")
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join("");
}

/** The published library uses camelCase while generated user APIs use PascalCase. */
export function toLibraryExportName(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_, character: string) => character.toUpperCase());
}

function internalImportName(theme: string, styleGroup: string, iconId: string): string {
  return `${toPascalCase(theme)}${toPascalCase(styleGroup)}${toPascalCase(iconId)}`;
}

const OWNER_HEADER =
  "// Generated by moeicons CLI. Do not edit manually; re-run `moeicons generate`.";

function appendReactFiles(
  files: GeneratedFile[],
  rel: (p: string) => string,
  config: MoeiconsConfigFile,
): void {
  files.push({
    path: rel("types.ts"),
    content: `${OWNER_HEADER}
export interface IconProps {
  className?: string;
  size?: number;
  strokeWidth?: number;
  "aria-label"?: string;
  [key: string]: unknown;
}
export type Theme =
${Object.keys(config.themes).map((theme) => `  | ${JSON.stringify(theme)}`).join("\n")};
`,
  });

  files.push({
    path: rel("registry.ts"),
    content: `${OWNER_HEADER}
 import type { IconProps, Theme } from "./types";
 import type * as React from "react";
 ${Object.entries(config.themes).map(([theme, entry]) => config.icons.map((iconId) => `import { ${toLibraryExportName(iconId)} as ${internalImportName(theme, entry.styleGroup, iconId)} } from "moe-icons/${config.tier}/react/${entry.styleGroup}";`).join("\n")).join("\n")}

export type IconId =
${config.icons.map((id) => `  | "${id}"`).join("\n")};

export interface ThemeRegistry {
${config.icons.map((id) => `  readonly ${toPascalCase(id)}: React.ComponentType<IconProps>;`).join("\n")}
}

export const registry: Record<Theme, ThemeRegistry> = {
${Object.keys(config.themes)
  .map((theme) => {
    const entry = config.themes[theme];
    if (!entry) throw new Error(`missing theme ${theme}`);
    return `  "${theme}": {\n${config.icons.map((id) => `    ${toPascalCase(id)}: ${internalImportName(theme, entry.styleGroup, id)},`).join("\n")}\n  },`;
  })
  .join("\n")}
};
`,
  });

  files.push({
    path: rel("provider.tsx"),
    content: `${OWNER_HEADER}
import { createContext, useContext, useState, type PropsWithChildren } from "react";
import type { Theme } from "./types";

interface MoeiconsThemeState { readonly theme: Theme; readonly setTheme: (theme: Theme) => void; }
const MoeiconsThemeContext = createContext<MoeiconsThemeState | undefined>(undefined);
export function MoeiconsProvider(props: PropsWithChildren<{ theme?: Theme }>) {
  const [theme, setTheme] = useState<Theme>(props.theme ?? ${JSON.stringify(config.defaultTheme)});
  return <MoeiconsThemeContext.Provider value={{ theme, setTheme }}>{props.children}</MoeiconsThemeContext.Provider>;
}
export function useMoeiconsTheme(): MoeiconsThemeState {
  const state = useContext(MoeiconsThemeContext);
  if (!state) throw new Error("useMoeiconsTheme must be used inside <MoeiconsProvider>");
  return state;
}
`,
  });

  for (const iconId of config.icons) {
    const pascal = toPascalCase(iconId);
    files.push({
      path: rel(`icons/${pascal}.tsx`),
      content: `${OWNER_HEADER}
import type { IconProps } from "../types";
import { registry } from "../registry";
import { useMoeiconsTheme } from "../provider";

export function ${pascal}(props: IconProps) {
  const { theme } = useMoeiconsTheme();
  const Component = registry[theme]?.${pascal} ?? registry[${JSON.stringify(config.defaultTheme)}].${pascal};
  return <Component {...props} />;
}
`,
    });
  }

  files.push({
    path: rel("index.ts"),
    content: `${OWNER_HEADER}
export type { IconProps } from "./types";
export { MoeiconsProvider, useMoeiconsTheme } from "./provider";
${config.icons.map((id) => `export { ${toPascalCase(id)} } from "./icons/${toPascalCase(id)}";`).join("\n")}
`,
  });
}

function appendVueFiles(
  files: GeneratedFile[],
  rel: (p: string) => string,
  config: MoeiconsConfigFile,
): void {
  files.push({
    path: rel("types.ts"),
    content: `${OWNER_HEADER}
export interface IconProps {
  class?: string;
  size?: number;
  strokeWidth?: number;
  "aria-label"?: string;
  [key: string]: unknown;
}
export type Theme =
${Object.keys(config.themes).map((theme) => `  | ${JSON.stringify(theme)}`).join("\n")};
`,
  });

  files.push({
    path: rel("theme.ts"),
    content: `${OWNER_HEADER}
import type { InjectionKey, Ref } from "vue";

export interface MoeiconsThemeState {
  readonly theme: Ref<string>;
  readonly setTheme: (theme: string) => void;
}

export const MOEICONS_THEME_KEY: InjectionKey<MoeiconsThemeState> = Symbol("moeicons-theme");
`,
  });

  files.push({
    path: rel("registry.ts"),
    content: `${OWNER_HEADER}
 import type { Component } from "vue";
 import type { Theme } from "./types";
 ${Object.entries(config.themes).map(([theme, entry]) => config.icons.map((iconId) => `import { ${toLibraryExportName(iconId)} as ${internalImportName(theme, entry.styleGroup, iconId)} } from "moe-icons/${config.tier}/vue/${entry.styleGroup}";`).join("\n")).join("\n")}

export type IconId =
${config.icons.map((id) => `  | "${id}"`).join("\n")};

export interface ThemeRegistry {
${config.icons.map((id) => `  readonly ${toPascalCase(id)}: Component;`).join("\n")}
}

export const registry: Record<Theme, ThemeRegistry> = {
${Object.keys(config.themes)
  .map((theme) => {
    const entry = config.themes[theme];
    if (!entry) throw new Error(`missing theme ${theme}`);
    return `  "${theme}": {\n${config.icons.map((id) => `    ${toPascalCase(id)}: ${internalImportName(theme, entry.styleGroup, id)},`).join("\n")}\n  },`;
  })
  .join("\n")}
};
`,
  });

  files.push({
    path: rel("provider.ts"),
    content: `${OWNER_HEADER}
import { defineComponent, h, provide, ref, type PropType } from "vue";
import { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "./theme";

export const MoeiconsProvider = defineComponent({
  name: "MoeiconsProvider",
  props: {
    theme: { type: String as PropType<string>, default: ${JSON.stringify(config.defaultTheme)} },
  },
  setup(props, { slots }) {
    const theme = ref<string>(props.theme);
    const setTheme = (next: string) => {
      theme.value = next;
    };
    const state: MoeiconsThemeState = { theme, setTheme };
    provide(MOEICONS_THEME_KEY, state);
    return () => slots.default?.();
  },
});
`,
  });

  files.push({
    path: rel("composable.ts"),
    content: `${OWNER_HEADER}
import { inject } from "vue";
import { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "./theme";

export function useMoeiconsTheme(): MoeiconsThemeState {
  const state = inject(MOEICONS_THEME_KEY);
  if (!state) {
    throw new Error("useMoeiconsTheme must be used inside <MoeiconsProvider>");
  }
  return state;
}
`,
  });

  for (const iconId of config.icons) {
    const pascal = toPascalCase(iconId);
    files.push({
      path: rel(`icons/${pascal}.ts`),
      content: `${OWNER_HEADER}
 import { computed, defineComponent, h, inject } from "vue";
import { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "../theme";
import { registry } from "../registry";
import type { Theme } from "../types";

export const ${pascal} = defineComponent({
  name: "${pascal}",
  setup(_props, { attrs }) {
    const state = inject<MoeiconsThemeState | undefined>(MOEICONS_THEME_KEY, undefined);
    const component = computed(() => registry[(state?.theme.value ?? ${JSON.stringify(config.defaultTheme)}) as Theme]?.${pascal} ?? registry[${JSON.stringify(config.defaultTheme)}].${pascal});
    return () =>
      h(component.value, attrs);
  },
});
`,
    });
  }

  files.push({
    path: rel("index.ts"),
    content: `${OWNER_HEADER}
export type { IconProps } from "./types";
export { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "./theme";
export { useMoeiconsTheme } from "./composable";
export { MoeiconsProvider } from "./provider";
${config.icons
  .map((id) => `export { ${toPascalCase(id)} } from "./icons/${toPascalCase(id)}";`)
  .join("\n")}
`,
  });
}

/**
 * Plan generated files for a config. Returns only owned paths under the config
 * output dir. Rejects duplicate PascalCase names and a config with no themes.
 */
export function planGeneratedFiles(
  config: MoeiconsConfigFile,
  outputDir: string,
): GenerationOutcome {
  const errors: string[] = [];
  if (Object.keys(config.themes).length === 0) {
    errors.push("config has no themes");
  }
  if (config.icons.length === 0) {
    errors.push("config has no icons");
  }

  const seen = new Map<string, string>();
  for (const iconId of config.icons) {
    const pascal = toPascalCase(iconId);
    const existing = seen.get(pascal);
    if (existing) {
      errors.push(`duplicate PascalCase name "${pascal}" from "${existing}" and "${iconId}"`);
    } else {
      seen.set(pascal, iconId);
    }
  }
  if (errors.length > 0) return { ok: false, errors };

  const files: GeneratedFile[] = [];
  const rel = (p: string) => `${outputDir.replace(/\/$/, "")}/${p}`;

  if (config.framework === "vue") {
    appendVueFiles(files, rel, config);
  } else {
    appendReactFiles(files, rel, config);
  }

  return { ok: true, files };
}
