import { catalog, findCatalogIcon, type IconCatalog } from "../catalog/catalog.js";
import type { MoeiconsConfigFile } from "../project/config.js";
import {
  reportLibraryExportNameCollisions,
  reportProxyNameCollisions,
  toLibraryExportName,
  toProxyName,
} from "../core/icon-names.js";
import { selectBitmapVariantAssets } from "../core/bitmap-assets.js";
import { createHash } from "node:crypto";
import { posix } from "node:path";
import { decodeUtf8 } from "../project/tar-gz.js";
import { prepareSvg, rootPaintAttributes, type SvgNode } from "./svg-model.js";
import { CN_HELPER_SOURCE } from "./cn.js";
import { resolveIconTheme, themeHasIcon } from "../core/icon-selection.js";
import {
  bitmapWrapperImportName,
  reactBitmapWrapperSource,
  resolveThemes,
  svgInternalImportName,
  vueBitmapWrapperSource,
  type ResolvedTheme,
} from "./theme-resolve.js";

export { toLibraryExportName, toProxyName };
/** @deprecated Use toProxyName; kept so existing generator tests keep compiling. */
export const toPascalCase = toProxyName;

/**
 * React/Vue proxy generation. Purely returns owned file paths/content for
 * types, provider/plugin, per-icon proxies and barrel exports. Rejects
 * duplicate PascalCase names and missing fallback. Bitmap themes use local
 * img wrappers + static asset imports (G1/G4); SVG themes import moe-icons.
 */

export interface GeneratedFile {
  readonly path: string;
  readonly content: string | Uint8Array;
}

export interface GenerationResult {
  readonly ok: true;
  readonly files: GeneratedFile[];
}

export interface GenerationError {
  readonly ok: false;
  readonly errors: string[];
}

export type GenerationOutcome = GenerationResult | GenerationError;

const OWNER_HEADER =
  "// Generated by moeicons CLI. Do not edit manually; re-run `moeicons generate`.";

/**
 * Vanilla project top-level index re-exports each selected style group as a
 * namespace (`export * as MoeOutline from './moe-outline'`), mirroring the
 * code-library layer. Two style groups must therefore never map to the same
 * namespace identifier, and the namespace must not shadow the reserved
 * runtime/types exports.
 */
function reportVanillaNamespaceCollisions(config: MoeiconsConfigFile): string[] {
  const reserved = new Set(["createMoeiconsRuntime", "Theme", "VanillaIconOptions", "default"]);
  const seen = new Map<string, string>();
  const problems: string[] = [];
  const styleGroups = [...new Set(Object.values(config.themes).map((entry) => entry.styleGroup))];
  for (const styleGroup of styleGroups) {
    const ns = toProxyName(styleGroup);
    if (reserved.has(ns)) {
      problems.push(`vanilla style group "${styleGroup}" maps to reserved export "${ns}"`);
      continue;
    }
    const owner = seen.get(ns);
    if (owner) {
      problems.push(
        `vanilla style groups "${owner}" and "${styleGroup}" both map to namespace "${ns}"`,
      );
    } else {
      seen.set(ns, styleGroup);
    }
  }
  return problems;
}

function themeClassExpr(themes: readonly ResolvedTheme[]): string {
  const entries = themes
    .map((theme) => {
      const className = theme.entry.className;
      return `  ${JSON.stringify(theme.theme)}: ${className === undefined ? "undefined" : JSON.stringify(className)},`;
    })
    .join("\n");
  return `const themeClassName: Partial<Record<Theme, string | undefined>> = {\n${entries}\n};\n`;
}

function themeDefaultsExpr(themes: readonly ResolvedTheme[]): string {
  return `const themeDefaultSize: Record<Theme, number> = {\n${themes.map((theme) => `  ${JSON.stringify(theme.theme)}: ${theme.entry.defaultSize ?? 24},`).join("\n")}\n};\n` +
    `const themeStrokeWidth: Partial<Record<Theme, number>> = {\n${themes.map((theme) => `  ${JSON.stringify(theme.theme)}: ${theme.entry.strokeWidth === undefined ? "undefined" : theme.entry.strokeWidth},`).join("\n")}\n};\n`;
}

function installedIconImport(outputDir: string, target: "react" | "vue", group: string, iconId: string): string {
  const file = `${toProxyName(iconId)}${target === "vue" ? ".vue" : ""}.js`;
  const relative = posix.relative(outputDir.replace(/\/$/, ""), `.moeicons/artifact/${target}/${group}/${file}`);
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function effectiveThemeForIcon(
  iconId: string,
  logical: ResolvedTheme,
  themes: readonly ResolvedTheme[],
  config: MoeiconsConfigFile,
  sourceCatalog: IconCatalog,
): ResolvedTheme {
  const selected = resolveIconTheme(config, sourceCatalog, logical.theme, iconId);
  const actual = themes.find((theme) => theme.theme === selected);
  if (!actual) throw new Error(`icon "${iconId}" has no selected variant for theme "${logical.theme}"`);
  return actual;
}

function appendReactFiles(
  files: GeneratedFile[],
  rel: (p: string) => string,
  config: MoeiconsConfigFile,
  themes: readonly ResolvedTheme[],
  sourceCatalog: IconCatalog,
): void {
  files.push({
    path: rel("cn.ts"),
    content: CN_HELPER_SOURCE,
  });

  files.push({
    path: rel("types.ts"),
    content: `${OWNER_HEADER}
import type * as React from "react";
export interface IconProps extends React.AriaAttributes, React.DOMAttributes<Element> {
  className?: string;
  style?: React.CSSProperties;
  size?: number;
  width?: number | string;
  height?: number | string;
  strokeWidth?: number;
  color?: string;
  fill?: string;
  stroke?: string;
  focusable?: boolean | "auto" | "true" | "false";
  alt?: string;
  title?: string;
  role?: React.AriaRole;
  draggable?: boolean;
  id?: string;
  tabIndex?: number;
}
export type Theme =
${Object.keys(config.themes)
  .map((theme) => `  | ${JSON.stringify(theme)}`)
  .join("\n")};
`,
  });

  // Each public icon proxy imports only its own theme variants. A generated
  // global registry would eagerly import every configured icon.
  for (const resolved of themes) {
    for (const iconId of config.icons) {
      const actual = effectiveThemeForIcon(iconId, resolved, themes, config, sourceCatalog);
      if (actual.kind !== "bitmap" || !actual.variant) continue;
      const wrapperName = bitmapWrapperImportName(resolved.theme, iconId);
      files.push({
        path: rel(`wrappers/${wrapperName}.tsx`),
        content: `${OWNER_HEADER}
${reactBitmapWrapperSource(iconId, wrapperName, actual.variant, resolved.entry.className)}`,
      });
    }
  }

  files.push({
    path: rel("provider.tsx"),
    content: `${OWNER_HEADER}
import { createContext, useCallback, useContext, useMemo, useState, type PropsWithChildren } from "react";
import type { Theme } from "./types";

interface MoeiconsThemeState { readonly theme: Theme; readonly setTheme: (theme: Theme) => void; }
const MoeiconsThemeContext = createContext<MoeiconsThemeState | undefined>(undefined);
const fallbackState: MoeiconsThemeState = { theme: ${JSON.stringify(config.defaultTheme)}, setTheme: () => {} };
export function MoeiconsProvider(props: PropsWithChildren<{ theme?: Theme; defaultTheme?: Theme; onThemeChange?: (theme: Theme) => void }>) {
  const [localTheme, setLocalTheme] = useState<Theme>(props.defaultTheme ?? ${JSON.stringify(config.defaultTheme)});
  const theme = props.theme ?? localTheme;
  const setTheme = useCallback((next: Theme) => {
    if (props.theme === undefined) setLocalTheme(next);
    props.onThemeChange?.(next);
  }, [props.theme, props.onThemeChange]);
  const value = useMemo(() => ({ theme, setTheme }), [theme, setTheme]);
  return <MoeiconsThemeContext.Provider value={value}>{props.children}</MoeiconsThemeContext.Provider>;
}
export function useMoeiconsTheme(): MoeiconsThemeState {
  return useContext(MoeiconsThemeContext) ?? fallbackState;
}
`,
  });

  for (const iconId of config.icons) {
    const pascal = toPascalCase(iconId);
    const ownImports = themes.map((theme) => {
      const actual = effectiveThemeForIcon(iconId, theme, themes, config, sourceCatalog);
      if (actual.kind === "bitmap") {
        const symbol = bitmapWrapperImportName(theme.theme, iconId);
        return `import { ${symbol} } from "../wrappers/${symbol}";`;
      }
      const symbol = svgInternalImportName(theme.theme, actual.entry.styleGroup, iconId);
      return `import ${symbol} from "${installedIconImport(posix.join(config.outputDir, "icons"), "react", actual.entry.styleGroup, iconId)}";`;
    }).join("\n");
    const renderBranches = themes.map((theme) => {
      const actual = effectiveThemeForIcon(iconId, theme, themes, config, sourceCatalog);
      const symbol = actual.kind === "bitmap"
        ? bitmapWrapperImportName(theme.theme, iconId)
        : svgInternalImportName(theme.theme, actual.entry.styleGroup, iconId);
      const refType = actual.kind === "bitmap" ? "HTMLImageElement" : "SVGSVGElement";
      return `    case ${JSON.stringify(theme.theme)}:
      return <${symbol} ref={ref as React.Ref<${refType}>} width={resolvedSize} height={resolvedSize} strokeWidth={strokeWidth ?? themeStrokeWidth[${JSON.stringify(theme.theme)}]} aria-label={rest["aria-label"] ?? alt} {...rest} className={cn("moe-icon", themeClassName[${JSON.stringify(theme.theme)}], className)} />;`;
    }).join("\n");
    const defaultTheme = themes.find((theme) => theme.theme === config.defaultTheme)!;
    const defaultActual = effectiveThemeForIcon(iconId, defaultTheme, themes, config, sourceCatalog);
    const defaultSymbol = defaultActual.kind === "bitmap"
      ? bitmapWrapperImportName(defaultTheme.theme, iconId)
      : svgInternalImportName(defaultTheme.theme, defaultActual.entry.styleGroup, iconId);
    const defaultRefType = defaultActual.kind === "bitmap" ? "HTMLImageElement" : "SVGSVGElement";
    const singleTheme = themes.length === 1;
    files.push({
      path: rel(`icons/${pascal}.tsx`),
      content: `${OWNER_HEADER}
import type { IconProps } from "../types";
${singleTheme ? "" : 'import { useMoeiconsTheme } from "../provider";'}
import { cn } from "../cn";
${singleTheme ? "" : 'import type { Theme } from "../types";'}
import * as React from "react";
${ownImports}

${singleTheme ? "" : themeClassExpr(themes)}
${singleTheme ? "" : themeDefaultsExpr(themes)}
export const ${pascal} = /* @__PURE__ */ React.forwardRef<SVGSVGElement | HTMLImageElement, IconProps>((props, ref) => {
  const { className, size, strokeWidth, alt, ...rest } = props;
${singleTheme ? `  return <${defaultSymbol} ref={ref as React.Ref<${defaultRefType}>} width={size ?? ${defaultTheme.entry.defaultSize ?? 24}} height={size ?? ${defaultTheme.entry.defaultSize ?? 24}} strokeWidth={strokeWidth ?? ${defaultTheme.entry.strokeWidth === undefined ? "undefined" : defaultTheme.entry.strokeWidth}} aria-label={rest["aria-label"] ?? alt} {...rest} className={cn("moe-icon", ${JSON.stringify(defaultTheme.entry.className ?? "")}, className)} />;` : `
  const { theme } = useMoeiconsTheme();
  const resolvedSize = size ?? themeDefaultSize[theme] ?? 24;
  switch (theme) {
${renderBranches}
    default:
      return <${defaultSymbol} ref={ref as React.Ref<${defaultRefType}>} width={resolvedSize} height={resolvedSize} strokeWidth={strokeWidth ?? themeStrokeWidth[${JSON.stringify(config.defaultTheme)}]} aria-label={rest["aria-label"] ?? alt} {...rest} className={cn("moe-icon", themeClassName[${JSON.stringify(config.defaultTheme)}], className)} />;
  }`}
});
`,
    });
  }

  files.push({
    path: rel("index.ts"),
    content: `${OWNER_HEADER}
export type { IconProps } from "./types";
export { cn } from "./cn";
export { MoeiconsProvider, useMoeiconsTheme } from "./provider";
${config.icons.map((id) => `export { ${toPascalCase(id)} } from "./icons/${toPascalCase(id)}";`).join("\n")}
`,
  });
}

function appendVueFiles(
  files: GeneratedFile[],
  rel: (p: string) => string,
  config: MoeiconsConfigFile,
  themes: readonly ResolvedTheme[],
  sourceCatalog: IconCatalog,
): void {
  files.push({
    path: rel("cn.ts"),
    content: CN_HELPER_SOURCE,
  });

  files.push({
    path: rel("types.ts"),
    content: `${OWNER_HEADER}
import type { SVGAttributes } from "vue";
export interface IconProps extends Omit<SVGAttributes, "class" | "focusable" | "draggable"> {
  class?: import("clsx").ClassValue;
  size?: number;
  width?: number | string;
  height?: number | string;
  strokeWidth?: number;
  color?: string;
  fill?: string;
  stroke?: string;
  focusable?: boolean | "auto" | "true" | "false";
  "aria-label"?: string;
  alt?: string;
  title?: string;
  "aria-hidden"?: boolean | "true" | "false";
  draggable?: boolean;
}

export type Theme =
${Object.keys(config.themes)
  .map((theme) => `  | ${JSON.stringify(theme)}`)
  .join("\n")};
`,
  });

  files.push({
    path: rel("theme.ts"),
    content: `${OWNER_HEADER}
import type { InjectionKey, Ref } from "vue";
import type { Theme } from "./types";

export interface MoeiconsThemeState {
  readonly theme: Ref<Theme>;
  readonly setTheme: (theme: Theme) => void;
}

export const MOEICONS_THEME_KEY: InjectionKey<MoeiconsThemeState> = Symbol("moeicons-theme");
`,
  });

  for (const resolved of themes) {
    for (const iconId of config.icons) {
      const actual = effectiveThemeForIcon(iconId, resolved, themes, config, sourceCatalog);
      if (actual.kind !== "bitmap" || !actual.variant) continue;
      const wrapperName = bitmapWrapperImportName(resolved.theme, iconId);
      files.push({
        path: rel(`wrappers/${wrapperName}.ts`),
        content: `${OWNER_HEADER}
${vueBitmapWrapperSource(iconId, wrapperName, actual.variant, resolved.entry.className)}`,
      });
    }
  }

  files.push({
    path: rel("provider.ts"),
    content: `${OWNER_HEADER}
import { computed, defineComponent, provide, ref, type PropType } from "vue";
import type { Theme } from "./types";
import { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "./theme";

export const MoeiconsProvider = defineComponent({
  name: "MoeiconsProvider",
  props: {
    theme: { type: String as PropType<Theme>, default: undefined },
    defaultTheme: { type: String as PropType<Theme>, default: ${JSON.stringify(config.defaultTheme)} as Theme },
  },
  emits: ["update:theme"],
  setup(props, { slots, emit }) {
    const localTheme = ref<Theme>(props.defaultTheme);
    const theme = computed<Theme>(() => props.theme ?? localTheme.value);
    const setTheme = (next: Theme) => {
      if (props.theme === undefined) localTheme.value = next;
      emit("update:theme", next);
    };
    const state: MoeiconsThemeState = { theme, setTheme };
    provide(MOEICONS_THEME_KEY, state);
    return () => slots.default?.();
  },
});
`,
  });

  files.push({
    path: rel("composable.ts"),
    content: `${OWNER_HEADER}
import { inject, ref } from "vue";
import { MOEICONS_THEME_KEY } from "./theme";
import type { MoeiconsThemeState } from "./theme";
import type { Theme } from "./types";

export function useMoeiconsTheme(): MoeiconsThemeState {
  const state = inject(MOEICONS_THEME_KEY, undefined);
  return state ?? { theme: ref<Theme>(${JSON.stringify(config.defaultTheme)}), setTheme: () => {} };
}
`,
  });

  for (const iconId of config.icons) {
    const pascal = toPascalCase(iconId);
    const ownImports = themes.map((theme) => {
      const actual = effectiveThemeForIcon(iconId, theme, themes, config, sourceCatalog);
      if (actual.kind === "bitmap") {
        const symbol = bitmapWrapperImportName(theme.theme, iconId);
        return `import { ${symbol} } from "../wrappers/${symbol}";`;
      }
      const symbol = svgInternalImportName(theme.theme, actual.entry.styleGroup, iconId);
      return `import ${symbol} from "${installedIconImport(posix.join(config.outputDir, "icons"), "vue", actual.entry.styleGroup, iconId)}";`;
    }).join("\n");
    const ownVariants = themes.map((theme) => {
      const actual = effectiveThemeForIcon(iconId, theme, themes, config, sourceCatalog);
      const symbol = actual.kind === "bitmap"
        ? bitmapWrapperImportName(theme.theme, iconId)
        : svgInternalImportName(theme.theme, actual.entry.styleGroup, iconId);
      return `  ${JSON.stringify(theme.theme)}: ${symbol},`;
    }).join("\n");
    const singleTheme = themes.length === 1;
    const onlyTheme = themes[0]!;
    const onlyActual = effectiveThemeForIcon(iconId, onlyTheme, themes, config, sourceCatalog);
    const onlySymbol = onlyActual.kind === "bitmap"
      ? bitmapWrapperImportName(onlyTheme.theme, iconId)
      : svgInternalImportName(onlyTheme.theme, onlyActual.entry.styleGroup, iconId);
    files.push({
      path: rel(`icons/${pascal}.ts`),
      content: `${OWNER_HEADER}
import { ${singleTheme ? "defineComponent, h" : "computed, defineComponent, h, inject, type Component"} } from "vue";
${singleTheme ? "" : 'import { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "../theme";'}
import { cn } from "../cn";
${singleTheme ? "" : 'import type { Theme } from "../types";'}
${ownImports}

${singleTheme ? "" : themeClassExpr(themes)}
${singleTheme ? "" : themeDefaultsExpr(themes)}
${singleTheme ? "" : `
const variants: Record<Theme, Component> = {
${ownVariants}
};`}

export const ${pascal} = /* @__PURE__ */ defineComponent({
  name: "${pascal}",
  inheritAttrs: false,
  props: {
    size: Number,
    width: [Number, String],
    height: [Number, String],
    strokeWidth: Number,
    color: String,
    fill: String,
    stroke: String,
    focusable: { type: [Boolean, String], default: undefined },
    alt: String,
    title: String,
    draggable: { type: Boolean, default: undefined },
  },
  setup(props, { attrs }) {
${singleTheme ? "" : `
    const state = inject<MoeiconsThemeState | undefined>(MOEICONS_THEME_KEY, undefined);
    const component = computed(() => variants[(state?.theme.value ?? ${JSON.stringify(config.defaultTheme)}) as Theme] ?? variants[${JSON.stringify(config.defaultTheme)}]);
`}
    return () => {
      const className = attrs.class as Parameters<typeof cn>[number];
      const size = props.size;
${singleTheme ? `
      const resolvedSize = size ?? ${onlyTheme.entry.defaultSize ?? 24};
      return h(${onlySymbol}, {
        ...attrs,
        ...(attrs["aria-label"] === undefined && props.alt === undefined ? {} : { "aria-label": attrs["aria-label"] ?? props.alt }),
        width: props.width ?? resolvedSize,
        height: props.height ?? resolvedSize,
        strokeWidth: props.strokeWidth ?? ${onlyTheme.entry.strokeWidth === undefined ? "undefined" : onlyTheme.entry.strokeWidth},
        ...(props.color === undefined ? {} : { color: props.color }),
        ...(props.fill === undefined ? {} : { fill: props.fill }),
        ...(props.stroke === undefined ? {} : { stroke: props.stroke }),
        ...(props.focusable === undefined ? {} : { focusable: props.focusable }),
        ...(props.alt === undefined ? {} : { alt: props.alt }),
        ...(props.title === undefined ? {} : { title: props.title }),
        ...(props.draggable === undefined ? {} : { draggable: props.draggable }),
        class: cn("moe-icon", ${JSON.stringify(onlyTheme.entry.className ?? "")}, className),
      });` : `
      const theme = (state?.theme.value ?? ${JSON.stringify(config.defaultTheme)}) as Theme;
      const resolvedSize = size ?? themeDefaultSize[theme] ?? 24;
      return h(component.value, {
        ...attrs,
        ...(attrs["aria-label"] === undefined && props.alt === undefined ? {} : { "aria-label": attrs["aria-label"] ?? props.alt }),
        width: props.width ?? resolvedSize,
        height: props.height ?? resolvedSize,
        strokeWidth: props.strokeWidth ?? themeStrokeWidth[theme],
        ...(props.color === undefined ? {} : { color: props.color }),
        ...(props.fill === undefined ? {} : { fill: props.fill }),
        ...(props.stroke === undefined ? {} : { stroke: props.stroke }),
        ...(props.focusable === undefined ? {} : { focusable: props.focusable }),
        ...(props.alt === undefined ? {} : { alt: props.alt }),
        ...(props.title === undefined ? {} : { title: props.title }),
        ...(props.draggable === undefined ? {} : { draggable: props.draggable }),
        class: cn("moe-icon", themeClassName[theme], className),
      });`}
    };
  },
});
`,
    });
  }

  files.push({
    path: rel("index.ts"),
    content: `${OWNER_HEADER}
export type { IconProps } from "./types";
export { cn } from "./cn";
export { MOEICONS_THEME_KEY, type MoeiconsThemeState } from "./theme";
export { useMoeiconsTheme } from "./composable";
export { MoeiconsProvider } from "./provider";
${config.icons
  .map((id) => `export { ${toPascalCase(id)} } from "./icons/${toPascalCase(id)}";`)
  .join("\n")}
`,
  });
}

function vanillaFactorySource(name: string, source: string, strategy: "outline" | "solid" | "mixed"): string {
  const parsed = prepareSvg(source, strategy);
  const paint = rootPaintAttributes(parsed.rootAttrs, strategy);
  const lines = [
    "const SVG_NS = 'http://www.w3.org/2000/svg';", "",
    "export interface VanillaIconOptions extends Record<string, string | number | undefined> { className?: string; strokeWidth?: number; }", "",
    `export function create${name}(options: VanillaIconOptions = {}): SVGElement {`,
    "  const svg = document.createElementNS(SVG_NS, 'svg');",
    `  svg.setAttribute('viewBox', ${JSON.stringify(parsed.viewBox)});`,
    "  svg.setAttribute('width', '24');",
    "  svg.setAttribute('height', '24');",
    "  svg.setAttribute('class', options.className ? `moe-icon ${options.className}` : 'moe-icon');",
  ];
  for (const [attr, value] of paint) lines.push(`  svg.setAttribute(${JSON.stringify(attr)}, ${JSON.stringify(value)});`);
  lines.push("  if (options.strokeWidth !== undefined) svg.setAttribute('stroke-width', String(options.strokeWidth));");
  lines.push("  for (const [name, value] of Object.entries(options)) if (name !== 'className' && name !== 'strokeWidth' && value !== undefined) svg.setAttribute(name, String(value));");
  let counter = 0;
  const emit = (nodes: readonly SvgNode[], parent: string): void => {
    for (const node of nodes) {
      if ("text" in node) { lines.push(`  ${parent}.appendChild(document.createTextNode(${JSON.stringify(node.text)}));`); continue; }
      const variable = `node${counter++}`;
      lines.push(`  const ${variable} = document.createElementNS(SVG_NS, ${JSON.stringify(node.name)});`);
      for (const [attr, value] of node.attrs) {
        const namespace = attr.startsWith("xlink:") ? "http://www.w3.org/1999/xlink" : attr.startsWith("xml:") ? "http://www.w3.org/XML/1998/namespace" : undefined;
        lines.push(namespace ? `  ${variable}.setAttributeNS(${JSON.stringify(namespace)}, ${JSON.stringify(attr)}, ${JSON.stringify(value)});` : `  ${variable}.setAttribute(${JSON.stringify(attr)}, ${JSON.stringify(value)});`);
      }
      emit(node.children, variable);
      lines.push(`  ${parent}.appendChild(${variable});`);
    }
  };
  emit(parsed.children, "svg");
  lines.push("  return svg;", "}", "", `export default create${name};`, "");
  return lines.join("\n");
}

/**
 * CLI project-layer Vanilla runtime (E2E-C4). Underlying code-library factories
 * stay theme-less; this runtime maps logical themes → style groups and updates
 * already-mounted DOM nodes on setTheme.
 */
function vanillaRuntimeSource(
  config: MoeiconsConfigFile,
  themes: readonly ResolvedTheme[],
  sourceCatalog: IconCatalog,
): string {
  const defaultTheme = config.defaultTheme;
  const imports: string[] = [];
  const factoryEntries: string[] = [];
  for (const resolved of themes) {
    const theme = resolved.theme;
    const iconEntries: string[] = [];
    for (const iconId of config.icons) {
      const group = effectiveThemeForIcon(iconId, resolved, themes, config, sourceCatalog).entry.styleGroup;
      const pascal = toPascalCase(iconId);
      const alias = `create${pascal}_${theme.replace(/[^a-zA-Z0-9]/g, "_")}`;
      imports.push(`import { create${pascal} as ${alias} } from "./${group}/${pascal}";`);
      iconEntries.push(`    ${JSON.stringify(iconId)}: ${alias}`);
    }
    factoryEntries.push(`  ${JSON.stringify(theme)}: {\n${iconEntries.join(",\n")}\n  }`);
  }
  return `${imports.join("\n")}
import type { Theme, VanillaIconOptions } from "./types";

const defaultTheme = ${JSON.stringify(defaultTheme)} as Theme;
const themeDefaults: Record<Theme, VanillaIconOptions> = {
${themes.map((theme) => `  ${JSON.stringify(theme.theme)}: { width: ${theme.entry.defaultSize ?? 24}, height: ${theme.entry.defaultSize ?? 24}${theme.entry.strokeWidth === undefined ? "" : `, strokeWidth: ${theme.entry.strokeWidth}`}${theme.entry.className === undefined ? "" : `, className: ${JSON.stringify(theme.entry.className)}`} },`).join("\n")}
};
const factories: Record<Theme, Record<string, (options?: VanillaIconOptions) => SVGElement>> = {
${factoryEntries.join(",\n")}
};

function resolveTheme(theme: string | undefined): Theme {
  if (theme && theme in factories) return theme as Theme;
  return defaultTheme;
}

function iconOptions(theme: Theme, options: VanillaIconOptions): VanillaIconOptions {
  return { ...themeDefaults[theme], ...options };
}

export interface MoeiconsRuntime {
  readonly getTheme: () => Theme;
  readonly setTheme: (theme: Theme | string) => void;
  readonly mount: (host: Element, iconId: string, options?: VanillaIconOptions) => MoeiconsMount;
  readonly mountIcon: (host: Element, iconId: string, options?: VanillaIconOptions) => SVGElement;
  readonly destroy: () => void;
}

export interface MoeiconsMount {
  readonly node: SVGElement;
  readonly update: (options: VanillaIconOptions) => void;
  readonly on: (type: string, listener: EventListener) => () => void;
  readonly unmount: () => void;
}

/** Project-layer runtime: theme ↔ styleGroup mapping with live DOM updates. */
export function createMoeiconsRuntime(options: { theme?: Theme | string } = {}): MoeiconsRuntime {
  let theme = resolveTheme(options.theme);
  const mounts = new Set<{ host: Element; iconId: string; options: VanillaIconOptions; node: SVGElement; listeners: Map<string, Set<EventListener>> }>();
  const render = (record: { iconId: string; options: VanillaIconOptions; node: SVGElement; listeners: Map<string, Set<EventListener>> }) => {
    const factory = factories[theme]?.[record.iconId] ?? factories[defaultTheme]?.[record.iconId];
    if (!factory) throw new Error(\`unknown icon "\${record.iconId}"\`);
    const nextNode = factory(iconOptions(theme, record.options));
    for (const [type, listeners] of record.listeners) for (const listener of listeners) nextNode.addEventListener(type, listener);
    record.node.replaceWith(nextNode);
    record.node = nextNode;
  };
  const mount = (host: Element, iconId: string, iconOptions: VanillaIconOptions = {}): MoeiconsMount => {
    const factory = factories[theme]?.[iconId] ?? factories[defaultTheme]?.[iconId];
    if (!factory) throw new Error(\`unknown icon "\${iconId}"\`);
    const record = { host, iconId, options: iconOptions, node: factory({ ...themeDefaults[theme], ...iconOptions }), listeners: new Map<string, Set<EventListener>>() };
    host.appendChild(record.node);
    mounts.add(record);
    return {
      get node() { return record.node; },
      update(next) { if (!mounts.has(record)) return; record.options = next; render(record); },
      on(type, listener) {
        if (!mounts.has(record)) return () => {};
        let listeners = record.listeners.get(type);
        if (!listeners) { listeners = new Set(); record.listeners.set(type, listeners); }
        listeners.add(listener);
        record.node.addEventListener(type, listener);
        return () => { record.listeners.get(type)?.delete(listener); record.node.removeEventListener(type, listener); };
      },
      unmount() { if (!mounts.has(record)) return; record.node.remove(); record.listeners.clear(); mounts.delete(record); },
    };
  };

  const api: MoeiconsRuntime = {
    getTheme: () => theme,
    setTheme(next) {
      const resolved = resolveTheme(next);
      if (resolved === theme) return;
      theme = resolved;
      for (const record of mounts) {
        if (!record.node.isConnected) { mounts.delete(record); continue; }
        render(record);
      }
    },
    mount,
    mountIcon(host, iconId, iconOptions = {}) {
      return mount(host, iconId, iconOptions).node;
    },
    destroy() {
      for (const mount of mounts) mount.node.remove();
      mounts.clear();
    },
  };
  return api;
}
`;
}

function archiveManifest(archiveFiles: Readonly<Record<string, Uint8Array>>): { path: string; assets: Array<{ path: string; size: number; sha256: string }> } | undefined {
  const entry = Object.entries(archiveFiles).find(([path]) => /(?:^|\/)assets\/manifest\.json$/.test(path));
  if (!entry) return undefined;
  try {
    const parsed = JSON.parse(decodeUtf8(entry[1])) as { schemaVersion?: unknown; assets?: Array<{ path?: unknown; size?: unknown; sha256?: unknown }> };
    if (parsed.schemaVersion !== 1 || !Array.isArray(parsed.assets)) return undefined;
    const assets = parsed.assets.filter((asset): asset is { path: string; size: number; sha256: string } => typeof asset.path === "string" && typeof asset.size === "number" && Number.isSafeInteger(asset.size) && asset.size >= 0 && typeof asset.sha256 === "string");
    return { path: entry[0], assets };
  } catch { return undefined; }
}

function sha256Hex(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function selectRawAssets(archiveFiles: Readonly<Record<string, Uint8Array>>, themes: readonly ResolvedTheme[], config: MoeiconsConfigFile, sourceCatalog: IconCatalog): { ok: true; assets: GeneratedFile[] } | { ok: false; errors: string[] } {
  const manifest = archiveManifest(archiveFiles);
  if (!manifest) return { ok: false, errors: ["installed artifact assets manifest is missing or invalid"] };
  const base = manifest.path.slice(0, manifest.path.lastIndexOf("/"));
  const wanted = new Set(themes.flatMap((theme) => config.icons.flatMap((icon) => {
    const actual = effectiveThemeForIcon(icon, theme, themes, config, sourceCatalog);
    return actual.kind === "svg" ? [`${actual.entry.styleGroup}/${icon}.svg`] : [];
  })));
  const assets: GeneratedFile[] = [];
  const errors: string[] = [];
  for (const path of wanted) {
    const entry = manifest.assets.find((asset) => asset.path === path);
    const bytes = entry ? archiveFiles[`${base}/${entry.path}`] ?? archiveFiles[entry.path] : undefined;
    if (!entry || !bytes) {
      errors.push(`raw asset missing: ${path}`);
      continue;
    }
    const sizeOk = bytes.byteLength === entry.size;
    const shaOk = sha256Hex(bytes) === entry.sha256.toLowerCase();
    if (!sizeOk || !shaOk) {
      errors.push(
        `raw asset verification failed for ${path}: expected size ${entry.size}/sha256 ${entry.sha256}, got size ${bytes.byteLength}/sha256 ${sha256Hex(bytes)}`,
      );
      continue;
    }
    assets.push({ path: `assets/${entry.path}`, content: bytes });
  }
  if (errors.length > 0) return { ok: false, errors };
  return { ok: true, assets };
}

/**
 * Plan generated files for a config. Returns only owned paths under the config
 * output dir. Rejects duplicate PascalCase names and a config with no themes.
 * Theme keys stay logical style themes; bitmap resourceVariantId never becomes a theme.
 */
export function planGeneratedFiles(
  config: MoeiconsConfigFile,
  outputDir: string,
  options: {
    readonly archiveFiles?: Readonly<Record<string, Uint8Array>>;
    readonly catalog?: IconCatalog;
  } = {},
): GenerationOutcome {
  const errors: string[] = [];
  if (Object.keys(config.themes).length === 0) {
    errors.push("config has no themes");
  }
  if (config.icons.length === 0) {
    errors.push("config has no icons");
  }

  errors.push(...reportProxyNameCollisions(config.icons));
  errors.push(...reportLibraryExportNameCollisions(config.icons));
  if (config.target === "vanilla") {
    errors.push(...reportVanillaNamespaceCollisions(config));
  }
  for (const iconId of config.icons) {
    const catalogIcon = findCatalogIcon(iconId, options.catalog ?? catalog);
    if (!catalogIcon) {
      errors.push(`unknown icon "${iconId}"`);
      continue;
    }
    for (const [theme, entry] of Object.entries(config.themes)) {
      if (!resolveIconTheme(config, options.catalog ?? catalog, theme, iconId)) errors.push(
        `icon "${iconId}" is not available in style group "${entry.styleGroup}" for theme "${theme}"; no selected variant satisfies missingIconPolicy`,
      );
    }
  }

  const resolved = resolveThemes(config, options.catalog ?? catalog);
  if (!resolved.ok) errors.push(...resolved.errors);
  if (errors.length > 0 || !resolved.ok) return { ok: false, errors };

  const files: GeneratedFile[] = [];
  const rel = (p: string) => `${outputDir.replace(/\/$/, "")}/${p}`;

  const target = config.target;
  if (target === "assets") {
    // Assets are a raw-resource target; never emit wrapper code for it.
  } else if (target === "vanilla") {
    if (resolved.themes.some((theme) => theme.kind === "bitmap")) {
      return { ok: false, errors: ["vanilla target supports SVG themes only"] };
    }
    if (options.archiveFiles === undefined) {
      return { ok: false, errors: ["vanilla target requires an installed artifact"] };
    }
    const raw = selectRawAssets(options.archiveFiles, resolved.themes, config, options.catalog ?? catalog);
    if (!raw.ok) return raw;
    const rawByPath = new Map(raw.assets.map((file) => [file.path.replace(/^assets\//, ""), file.content]));
    const archivePaths = new Set(Object.keys(options.archiveFiles));
    const groups = new Set(resolved.themes.map((theme) => theme.entry.styleGroup));
    files.push({ path: rel("types.ts"), content: "export interface VanillaIconOptions extends Record<string, string | number | undefined> { className?: string; strokeWidth?: number; }\nexport type Theme = " + Object.keys(config.themes).map((t) => JSON.stringify(t)).join(" | ") + ";\n" });
    for (const styleGroup of groups) {
      const exports: string[] = ["// Vanilla factory exports"];
      for (const iconId of config.icons.filter((id) => resolved.themes.some((theme) => theme.entry.styleGroup === styleGroup && themeHasIcon(config, options.catalog ?? catalog, theme.theme, id)))) {
        const name = toPascalCase(iconId);
        const source = rawByPath.get(`${styleGroup}/${iconId}.svg`);
        if (!source || typeof source === "string") return { ok: false, errors: [`raw asset missing: ${styleGroup}/${iconId}.svg`] };
        const kind = resolved.themes.find((theme) => theme.entry.styleGroup === styleGroup)?.group.type;
        const strategy = kind === "outline" || kind === "solid" ? kind : "mixed";
        const artifactPath = `.moeicons/artifact/vanilla/${styleGroup}/${name}.js`;
        const archiveHasFactory = archivePaths.has(`vanilla/${styleGroup}/${name}.js`) ||
          archivePaths.has(`${config.tier}/vanilla/${styleGroup}/${name}.js`);
        const imported = posix.relative(posix.join(outputDir, styleGroup), artifactPath);
        const specifier = imported.startsWith(".") ? imported : `./${imported}`;
        files.push({ path: rel(`${styleGroup}/${name}.ts`), content: archiveHasFactory
          ? `${OWNER_HEADER}\nexport { create${name}, default } from ${JSON.stringify(specifier)};\n`
          : vanillaFactorySource(name, decodeUtf8(source), strategy) });
        exports.push(`export { default as ${toLibraryExportName(iconId)}, create${name} } from './${name}';`);
      }
      files.push({ path: rel(`${styleGroup}/index.ts`), content: `${exports.join("\n")}\n` });
    }
    files.push({
      path: rel("runtime.ts"),
      content: vanillaRuntimeSource(config, resolved.themes, options.catalog ?? catalog),
    });
    const groupNamespaces = [...groups].map((group) => {
      const ns = toProxyName(group);
      return `export * as ${ns} from './${group}';`;
    });
    files.push({
      path: rel("index.ts"),
      content: `${groupNamespaces.join("\n")}\nexport { createMoeiconsRuntime } from './runtime';\nexport type { Theme, VanillaIconOptions } from './types';\n`,
    });
  } else if (target === "vue") {
    appendVueFiles(files, rel, config, resolved.themes, options.catalog ?? catalog);
  } else {
    appendReactFiles(files, rel, config, resolved.themes, options.catalog ?? catalog);
  }

  if (target === "assets") {
    if (options.archiveFiles === undefined) {
      return { ok: false, errors: ["assets target requires an installed artifact"] };
    }
    const raw = selectRawAssets(options.archiveFiles, resolved.themes, config, options.catalog ?? catalog);
    if (!raw.ok) return raw;
    for (const asset of raw.assets) files.push({ path: rel(asset.path), content: asset.content });
  }

  const bitmapThemes = resolved.themes.filter((theme) => theme.kind === "bitmap" && theme.variant);
  if (bitmapThemes.length > 0) {
    const variants = bitmapThemes.flatMap((theme) => (theme.variant ? [theme.variant] : []));
    const unique = [
      ...new Map(variants.map((variant) => [variant.resourceVariantId, variant])).values(),
    ];
    if (options.archiveFiles === undefined) {
      return {
        ok: false,
        errors: [
          "bitmap themes require a downloaded free artifact; run `moeicons install` or provide a local archive fixture",
        ],
      };
    }
    // Exact catalog variants are the v2 evidence. Frozen v1 catalogs did not
    // carry this field and therefore use only the explicit legacy parser. A
    // mixed archive/catalog state is ambiguous and must not be guessed.
    const mediaModes = new Set(bitmapThemes.map((theme) =>
      theme.group.variants && theme.group.variants.length > 0 ? 2 : 1));
    if (mediaModes.size !== 1) {
      return { ok: false, errors: ["bitmap themes mix v1 and v2 catalog contracts"] };
    }
    const mediaContractVersion = [...mediaModes][0] as 1 | 2;
    const selected = selectBitmapVariantAssets(
      options.archiveFiles,
      unique,
      config.icons,
      { mediaContractVersion, requestedPairs: resolved.themes.flatMap((theme) =>
        config.icons.flatMap((iconId) => {
          const actual = effectiveThemeForIcon(iconId, theme, resolved.themes, config, options.catalog ?? catalog);
          return actual.variant ? [{ variantId: actual.variant.resourceVariantId, iconId }] : [];
        })) },
    );
    if (!selected.ok) return { ok: false, errors: [...selected.errors] };
    for (const asset of selected.assets) {
      files.push({ path: rel(asset.destRel), content: asset.bytes });
    }
  }

  if (target === "assets") {
    const manifestAssets = files
      .filter((file) => file.path.startsWith(`${outputDir.replace(/\/$/, "")}/assets/`) && !file.path.endsWith("/manifest.json"))
      .map((file) => {
        const path = file.path.slice(`${outputDir.replace(/\/$/, "")}/assets/`.length);
        const bytes = typeof file.content === "string" ? Buffer.from(file.content, "utf8") : Buffer.from(file.content);
        return { path, size: bytes.byteLength, sha256: createHash("sha256").update(bytes).digest("hex") };
      })
      .sort((a, b) => a.path.localeCompare(b.path));
    files.push({ path: rel("assets/manifest.json"), content: `${JSON.stringify({ schemaVersion: 1, assets: manifestAssets }, null, 2)}\n` });
  }

  return { ok: true, files };
}
